#!/bin/bash
#SBATCH --job-name=mcr2eval
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --gres=gpu:2080ti:1
#SBATCH --mem=16GB
#SBATCH --time=48:00:00
#SBATCH --partition=bharath

# OPTIONAL: uncomment this if you're using an anaconda environment named <my_env_name>
. /home/zw287/anaconda3/etc/profile.d/conda.sh
conda activate mcr2

cd $HOME/mcr2; python evaluate_seq.py --nearsub --cpb 10 --label_batch 9 --model_dir saved_models/seqsup_resnet18+128_cifar100_cpb10_epo100_bs1000_lr0.01_mom0.9_wd0.0005_gam11.0_gam21.0_eps0.5_lcr0.0